### PR TITLE
Add styling and refactor button component 

### PR DESCRIPTION
**Pull request by GiuliaTeggi**

### CODE REVIEW

**Comment by haydnba** [comment]
Hi Giulia - looking at the travis log the reason this build failed is because some of the tests on the `getVolunteer` queries timed out - this is even in spite of the fact I explicitly doubled the timeout threshold from within the test suite. It might have been because of connection problems or something so try to push again and if it doesn't pass I'll have to try to rewrite the tests and you can merge an update before you push again. 😣

**Comment by GiuliaTeggi** [comment]
All checks have passed now! :relaxed:

**Review by haydnba — APPROVED** [review]
Amazing and very good that the build passed this time!

**Comment by haydnba** [comment]
👍

**Pull request merged**
